server:
  port: 8080
spring:
#  sql:
#    init:
#      mode:
#        always
  application:
    name: stock
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/stock
    username: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

